<?php

namespace App\Http\Classes\sbcdb;

use Illuminate\Http\Request;
use App\Http\Requests;
use Session;

use App\Http\Classes\coreFunctions;

class fams
{
  private $coreFunctions;

  public function __construct()
  {
    $this->coreFunctions = new coreFunctions;
  } //end fn


  public function tableupdatefams()
  {
    $qry = "CREATE TABLE generalitem (
            line int(11) unsigned NOT NULL AUTO_INCREMENT,
            barcode varchar(20) NOT NULL DEFAULT '',
            uom varchar(10) NOT NULL DEFAULT '',
            itemname varchar(100) NOT NULL DEFAULT '',
            groupid int(11) unsigned NOT NULL DEFAULT '0',
            subgroup varchar(100) NOT NULL DEFAULT '',
            modelid int(11) unsigned NOT NULL DEFAULT '0',
            brandid int(11) unsigned NOT NULL DEFAULT '0',
            classid int(11) unsigned NOT NULL DEFAULT '0',
            sizeid varchar(100) NOT NULL DEFAULT '',
            company varchar(45) NOT NULL DEFAULT '',
            createdate datetime DEFAULT NULL,
            createby varchar(45) NOT NULL DEFAULT '',
            editdate datetime DEFAULT NULL,
            editby varchar(45) NOT NULL DEFAULT '',
            type varchar(45) NOT NULL DEFAULT '',
            PRIMARY KEY (line)
            ) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
    $this->coreFunctions->sbccreatetable("generalitem", $qry);

    $this->coreFunctions->sbcaddcolumn("generalitem", "brandid", "int(11) NOT NULL DEFAULT '0'", 0);
    $this->coreFunctions->sbcaddcolumn("generalitem", "sizeid", "varchar(100) NOT NULL DEFAULT ''", 0);
    $this->coreFunctions->sbcaddcolumn("generalitem", "editdate", "DATETIME DEFAULT NULL", 0);
    $this->coreFunctions->sbcaddcolumn("generalitem", "editby", "varchar(100) NOT NULL DEFAULT ''", 0);

    $qry = "CREATE TABLE `issueitem` (
            `line` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `clientid` int(11) unsigned NOT NULL DEFAULT '0',
            `locid` int(11) unsigned NOT NULL DEFAULT '0',
            `itemid` int(11) unsigned NOT NULL DEFAULT '0',
            `dateid` datetime DEFAULT NULL,
            `createdate` datetime DEFAULT NULL,
            `createby` varchar(45) NOT NULL DEFAULT '',
            `type` varchar(45) NOT NULL DEFAULT '',
            `rem` varchar(500) NOT NULL DEFAULT '',
            PRIMARY KEY (`line`)
            ) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
    $this->coreFunctions->sbccreatetable("issueitem", $qry);

    $qry = "CREATE TABLE `gphead` (
          `trno` bigint(20) NOT NULL DEFAULT '0',
          `doc` char(2) NOT NULL DEFAULT '',
          `docno` char(20) NOT NULL,
          `client` varchar(15) NOT NULL DEFAULT '',
          `clientname` varchar(150) DEFAULT NULL,
          `address` varchar(150) DEFAULT NULL,
          `shipto` varchar(100) DEFAULT NULL,
          `tel` varchar(50) DEFAULT NULL,
          `dateid` datetime DEFAULT NULL,
          `due` datetime DEFAULT NULL,
          `wh` varchar(15) DEFAULT NULL,
          `terms` varchar(30) DEFAULT NULL,
          `rem` varchar(500) DEFAULT NULL,
          `cur` varchar(3) NOT NULL DEFAULT '',
          `forex` decimal(18,2) DEFAULT '0.00',
          `voiddate` datetime DEFAULT NULL,
          `branch` varchar(30) DEFAULT NULL,
          `agent` varchar(50) NOT NULL DEFAULT '',
          `yourref` varchar(25) NOT NULL DEFAULT '',
          `ourref` varchar(25) NOT NULL DEFAULT '',
          `approvedby` varchar(100) NOT NULL DEFAULT '',
          `approveddate` datetime DEFAULT NULL,
          `printtime` datetime DEFAULT NULL,
          `lockuser` varchar(100) NOT NULL DEFAULT '',
          `lockdate` datetime DEFAULT NULL,
          `openby` varchar(100) NOT NULL DEFAULT '',
          `users` varchar(100) NOT NULL DEFAULT '',
          `createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          `createby` varchar(100) NOT NULL DEFAULT '',
          `editby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `viewby` varchar(100) NOT NULL DEFAULT '',
          `viewdate` datetime DEFAULT NULL,
          `mop` varchar(60) NOT NULL DEFAULT '',
          `modamt` decimal(18,2) NOT NULL DEFAULT '0.00',
          `moddate` datetime DEFAULT NULL,
          `modref` varchar(60) NOT NULL DEFAULT '',
          `salestype` varchar(25) DEFAULT '',
          `trnx_type` varchar(45) NOT NULL DEFAULT '',
          `projectid` int(10) unsigned NOT NULL DEFAULT '0',
          `deliverysite` varchar(500) NOT NULL DEFAULT '',
          `deliverydatetime` varchar(100) NOT NULL DEFAULT '',
          `areceiver` varchar(100) NOT NULL DEFAULT '',
          `areceivercontact` varchar(50) NOT NULL DEFAULT '',
          `reqpacking` varchar(45) NOT NULL DEFAULT '',
          `freightcharge` varchar(45) NOT NULL DEFAULT '',
          `freightchargedecval` varchar(45) NOT NULL DEFAULT '',
          `faccountof` varchar(10) NOT NULL DEFAULT '',
          `mannerofpayment` varchar(10) NOT NULL DEFAULT '',
          `servicemode` varchar(10) NOT NULL DEFAULT '',
          `ispartialdelivery` int(10) unsigned NOT NULL DEFAULT '0',
          `reqinspection` varchar(100) NOT NULL DEFAULT '',
          `documenttouse` varchar(100) NOT NULL DEFAULT '',
          `mnlarrastre` varchar(10) NOT NULL DEFAULT '',
          `lede_rem` varchar(1000) NOT NULL DEFAULT '',
          `rdate` varchar(45) NOT NULL DEFAULT '',
          `rtype` varchar(45) NOT NULL DEFAULT '',
          `uv_transtype` varchar(25) NOT NULL DEFAULT '',
          `uv_amountreceived` varchar(25) NOT NULL DEFAULT '',
          `uv_picker` varchar(45) NOT NULL DEFAULT '',
          `uv_checker` varchar(45) NOT NULL DEFAULT '',
          `uv_pickername` varchar(45) NOT NULL DEFAULT '',
          `uv_checkername` varchar(45) NOT NULL DEFAULT '',
          `vattype` varchar(25) NOT NULL DEFAULT '',
          `pdate` datetime DEFAULT NULL,
          `orun` varchar(45) NOT NULL DEFAULT '',
          `urun` varchar(45) NOT NULL DEFAULT '',
          `creditinfo` varchar(1000) NOT NULL DEFAULT '',
          `crline` decimal(18,2) NOT NULL DEFAULT '0.00',
          `overdue` decimal(18,2) NOT NULL DEFAULT '0.00',
          `subproject` int(11) NOT NULL DEFAULT '0',
          `stageid` int(11) NOT NULL DEFAULT '0',
          `forwarder` varchar(70) NOT NULL DEFAULT '',
          PRIMARY KEY (`trno`)
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("gphead", $qry);

    $qry = "CREATE TABLE `hgphead` (
          `trno` bigint(20) NOT NULL DEFAULT '0',
          `doc` char(2) NOT NULL DEFAULT '',
          `docno` char(20) NOT NULL,
          `client` varchar(15) NOT NULL DEFAULT '',
          `clientname` varchar(150) DEFAULT NULL,
          `address` varchar(150) DEFAULT NULL,
          `shipto` varchar(150) DEFAULT NULL,
          `tel` varchar(50) DEFAULT NULL,
          `dateid` datetime DEFAULT NULL,
          `due` datetime DEFAULT NULL,
          `wh` varchar(15) DEFAULT NULL,
          `terms` varchar(30) DEFAULT NULL,
          `rem` varchar(500) DEFAULT NULL,
          `cur` varchar(3) NOT NULL DEFAULT '',
          `forex` decimal(18,2) DEFAULT '0.00',
          `voiddate` datetime DEFAULT NULL,
          `branch` varchar(30) DEFAULT NULL,
          `agent` varchar(50) NOT NULL DEFAULT '',
          `yourref` varchar(25) NOT NULL DEFAULT '',
          `ourref` varchar(25) NOT NULL DEFAULT '',
          `approvedby` varchar(100) NOT NULL DEFAULT '',
          `approveddate` datetime DEFAULT NULL,
          `printtime` datetime DEFAULT NULL,
          `lockuser` varchar(100) NOT NULL DEFAULT '',
          `lockdate` datetime DEFAULT NULL,
          `openby` varchar(100) NOT NULL DEFAULT '',
          `users` varchar(100) NOT NULL DEFAULT '',
          `createdate` datetime DEFAULT NULL,
          `createby` varchar(100) NOT NULL DEFAULT '',
          `editby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `viewby` varchar(100) NOT NULL DEFAULT '',
          `viewdate` datetime DEFAULT NULL,
          `mop` varchar(60) NOT NULL DEFAULT '',
          `modamt` decimal(18,2) NOT NULL DEFAULT '0.00',
          `moddate` datetime DEFAULT NULL,
          `modref` varchar(60) NOT NULL DEFAULT '',
          `salestype` varchar(25) DEFAULT '',
          `isapproved` int(10) unsigned NOT NULL DEFAULT '0',
          `reason1` varchar(500) NOT NULL DEFAULT '',
          `reason2` varchar(500) NOT NULL DEFAULT '',
          `rfno` varchar(45) NOT NULL DEFAULT '0',
          `rf_approval` varchar(45) NOT NULL DEFAULT '',
          `trnx_type` varchar(45) NOT NULL DEFAULT '',
          `projectid` int(10) unsigned NOT NULL DEFAULT '0',
          `deliverysite` varchar(500) NOT NULL DEFAULT '',
          `deliverydatetime` varchar(100) NOT NULL DEFAULT '',
          `areceiver` varchar(100) NOT NULL DEFAULT '',
          `areceivercontact` varchar(50) NOT NULL DEFAULT '',
          `reqpacking` varchar(45) NOT NULL DEFAULT '',
          `freightcharge` varchar(45) NOT NULL DEFAULT '',
          `freightchargedecval` varchar(45) NOT NULL DEFAULT '',
          `faccountof` varchar(10) NOT NULL DEFAULT '',
          `mannerofpayment` varchar(10) NOT NULL DEFAULT '',
          `servicemode` varchar(10) NOT NULL DEFAULT '',
          `ispartialdelivery` varchar(10) NOT NULL DEFAULT '',
          `reqinspection` varchar(10) NOT NULL DEFAULT '',
          `documenttouse` varchar(10) NOT NULL DEFAULT '',
          `mnlarrastre` varchar(10) NOT NULL DEFAULT '',
          `lede_rem` varchar(1000) NOT NULL DEFAULT '',
          `rdate` varchar(45) NOT NULL DEFAULT '',
          `rtype` varchar(45) NOT NULL DEFAULT '',
          `uv_transtype` varchar(25) NOT NULL DEFAULT '',
          `uv_amountreceived` varchar(25) NOT NULL DEFAULT '',
          `uv_picker` varchar(45) NOT NULL DEFAULT '',
          `uv_checker` varchar(45) NOT NULL DEFAULT '',
          `uv_pickername` varchar(45) NOT NULL DEFAULT '',
          `uv_checkername` varchar(45) NOT NULL DEFAULT '',
          `isfailed` int(10) NOT NULL DEFAULT '0',
          `vattype` varchar(25) NOT NULL DEFAULT '',
          `pdate` datetime DEFAULT NULL,
          `orun` varchar(45) NOT NULL DEFAULT '',
          `urun` varchar(45) NOT NULL DEFAULT '',
          `creditinfo` varchar(1000) NOT NULL DEFAULT '',
          `crline` decimal(18,2) NOT NULL DEFAULT '0.00',
          `overdue` decimal(18,2) NOT NULL DEFAULT '0.00',
          `subproject` int(11) NOT NULL DEFAULT '0',
          `stageid` int(11) NOT NULL DEFAULT '0',
          `forwarder` varchar(70) NOT NULL DEFAULT '',
          PRIMARY KEY (`trno`)
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("hgphead", $qry);

    $qry = "CREATE TABLE `gpstock` (
          `trno` bigint(20) NOT NULL DEFAULT '0',
          `line` int(11) NOT NULL,
          `uom` varchar(15) DEFAULT NULL,
          `disc` varchar(40) NOT NULL DEFAULT '',
          `rem` varchar(500) NOT NULL DEFAULT '',
          `amt` decimal(19,6) unsigned NOT NULL DEFAULT '0.000000',
          `isqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `isamt` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `iss` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `ext` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `qa` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `void` tinyint(4) NOT NULL DEFAULT '0',
          `encodeddate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          `encodedby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `editby` varchar(100) NOT NULL DEFAULT '',
          `loc` varchar(45) NOT NULL DEFAULT '',
          `expiry` varchar(45) DEFAULT NULL,
          `fstatus` varchar(45) NOT NULL DEFAULT '',
          `wh_currentqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `mrsqa` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `kgs` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `itemid` int(11) NOT NULL DEFAULT '0',
          `whid` int(11) NOT NULL DEFAULT '0',
          `refx` int(11) NOT NULL DEFAULT '0',
          `linex` int(11) NOT NULL DEFAULT '0',
          `poqa` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `ref` varchar(50) NOT NULL DEFAULT '',
          `oqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `substage` int(11) NOT NULL DEFAULT '0',
          `projectid` int(3) NOT NULL DEFAULT '0',
          `stageid` int(3) NOT NULL DEFAULT '0',
          `subactivity` int(11) NOT NULL DEFAULT '0',
          PRIMARY KEY (`trno`,`line`)
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("gpstock", $qry);
    $this->coreFunctions->sbcaddcolumn("gpstock", "serialno", "varchar(100) NOT NULL DEFAULT ''", 0);

    $qry = "CREATE TABLE `hgpstock` (
          `trno` bigint(20) NOT NULL DEFAULT '0',
          `line` int(11) NOT NULL,
          `uom` varchar(15) DEFAULT NULL,
          `disc` varchar(40) NOT NULL DEFAULT '',
          `rem` varchar(40) NOT NULL DEFAULT '',
          `amt` decimal(19,6) unsigned NOT NULL DEFAULT '0.000000',
          `isqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `isamt` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `iss` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `ext` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `qa` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `void` tinyint(4) NOT NULL DEFAULT '0',
          `encodeddate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          `encodedby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `editby` varchar(100) NOT NULL DEFAULT '',
          `loc` varchar(45) NOT NULL DEFAULT '',
          `expiry` varchar(45) DEFAULT NULL,
          `fstatus` varchar(45) NOT NULL DEFAULT '',
          `wh_currentqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `mrsqa` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `isfailed` int(10) NOT NULL DEFAULT '0',
          `kgs` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `itemid` int(11) NOT NULL DEFAULT '0',
          `whid` int(11) NOT NULL DEFAULT '0',
          `refx` int(11) NOT NULL DEFAULT '0',
          `linex` int(11) NOT NULL DEFAULT '0',
          `ref` varchar(50) NOT NULL DEFAULT '',
          `poqa` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `oqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `substage` int(11) NOT NULL DEFAULT '0',
          `projectid` int(3) NOT NULL DEFAULT '0',
          `stageid` int(3) NOT NULL DEFAULT '0',
          `subactivity` int(11) NOT NULL DEFAULT '0',
          PRIMARY KEY (`trno`,`line`)
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("hgpstock", $qry);
    $this->coreFunctions->sbcaddcolumn("hgpstock", "serialno", "varchar(100) NOT NULL DEFAULT ''", 0);
    $this->coreFunctions->sbcaddcolumn("hgpstock", "returnby", "varchar(100) NOT NULL DEFAULT ''", 0);
    $this->coreFunctions->sbcaddcolumn("hgpstock", "returndate", "DATETIME DEFAULT NULL", 0);

    $this->coreFunctions->sbcaddcolumn("pcstock", "consignee", "varchar(100) NOT NULL DEFAULT ''", 0);
    $this->coreFunctions->sbcaddcolumn("hpcstock", "consignee", "varchar(100) NOT NULL DEFAULT ''", 0);

    $qry = "CREATE TABLE `pfhead` (
          `trno` bigint(20) NOT NULL DEFAULT '0',
          `doc` char(2) NOT NULL DEFAULT '',
          `docno` char(20) NOT NULL,
          `client` varchar(15) NOT NULL DEFAULT '',
          `clientname` varchar(150) NOT NULL DEFAULT '',
          `address` varchar(150) NOT NULL DEFAULT '',
          `shipto` varchar(150) NOT NULL DEFAULT '',
          `tel` varchar(50) NOT NULL DEFAULT '',
          `dateid` datetime DEFAULT NULL,
          `due` datetime DEFAULT NULL,
          `wh` varchar(15) NOT NULL DEFAULT '',
          `terms` varchar(30) NOT NULL DEFAULT '',
          `rem` mediumtext NOT NULL,
          `cur` varchar(3) NOT NULL DEFAULT '',
          `forex` decimal(18,2) NOT NULL DEFAULT '0.00',
          `voiddate` datetime DEFAULT NULL,
          `branch` int(10) NOT NULL DEFAULT '0',
          `agent` varchar(20) NOT NULL DEFAULT '',
          `isimport` tinyint(4) NOT NULL DEFAULT '0',
          `delby` datetime DEFAULT NULL,
          `yourref` varchar(25) NOT NULL DEFAULT '',
          `ourref` varchar(25) NOT NULL DEFAULT '',
          `vattype` varchar(45) NOT NULL DEFAULT '',
          `isapproved` tinyint(4) NOT NULL DEFAULT '0',
          `lockuser` varchar(100) NOT NULL DEFAULT '',
          `lockdate` datetime DEFAULT NULL,
          `openby` varchar(100) NOT NULL DEFAULT '',
          `users` varchar(100) NOT NULL DEFAULT '',
          `createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          `createby` varchar(100) NOT NULL DEFAULT '',
          `editby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `viewby` varchar(100) NOT NULL DEFAULT '',
          `viewdate` datetime DEFAULT NULL,
          `projectid` int(11) NOT NULL DEFAULT '0',
          `subproject` int(11) NOT NULL DEFAULT '0',
          `deptid` int(10) NOT NULL DEFAULT '0',
          `tax` int(11) NOT NULL DEFAULT '0',
          `shipcontactid` int(11) NOT NULL DEFAULT '0',
          `billcontactid` int(11) NOT NULL DEFAULT '0',
          `empid` int(11) NOT NULL DEFAULT '0',
          `sotrno` int(11) NOT NULL DEFAULT '0',
          `shipid` int(11) NOT NULL DEFAULT '0',
          `billid` int(11) NOT NULL DEFAULT '0',
          `revision` varchar(100) NOT NULL DEFAULT '',
          `deldate` datetime DEFAULT NULL,
          `deladdress` varchar(200) NOT NULL DEFAULT '',
          `rqtrno` int(11) NOT NULL DEFAULT '0',
          PRIMARY KEY (`trno`),
          KEY `Index_2head` (`docno`,`client`,`dateid`,`due`)
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("pfhead", $qry);

    $qry = "CREATE TABLE `hpfhead` (
          `trno` bigint(20) NOT NULL DEFAULT '0',
          `doc` char(2) NOT NULL DEFAULT '',
          `docno` char(20) NOT NULL,
          `client` varchar(15) NOT NULL DEFAULT '',
          `clientname` varchar(150) NOT NULL DEFAULT '',
          `address` varchar(150) NOT NULL DEFAULT '',
          `shipto` varchar(150) NOT NULL DEFAULT '',
          `tel` varchar(50) NOT NULL DEFAULT '',
          `dateid` datetime DEFAULT NULL,
          `due` datetime DEFAULT NULL,
          `wh` varchar(15) NOT NULL DEFAULT '',
          `terms` varchar(30) NOT NULL DEFAULT '',
          `rem` mediumtext NOT NULL,
          `cur` varchar(3) NOT NULL DEFAULT '',
          `forex` decimal(18,2) NOT NULL DEFAULT '0.00',
          `voiddate` datetime DEFAULT NULL,
          `branch` int(10) NOT NULL DEFAULT '0',
          `agent` varchar(20) NOT NULL DEFAULT '',
          `isimport` tinyint(4) NOT NULL DEFAULT '0',
          `delby` datetime DEFAULT NULL,
          `yourref` varchar(25) NOT NULL DEFAULT '',
          `ourref` varchar(25) NOT NULL DEFAULT '',
          `vattype` varchar(45) NOT NULL DEFAULT '',
          `isapproved` tinyint(4) NOT NULL DEFAULT '0',
          `lockuser` varchar(100) NOT NULL DEFAULT '',
          `lockdate` datetime DEFAULT NULL,
          `openby` varchar(100) NOT NULL DEFAULT '',
          `users` varchar(100) NOT NULL DEFAULT '',
          `createdate` datetime DEFAULT NULL,
          `createby` varchar(100) NOT NULL DEFAULT '',
          `editby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `viewby` varchar(100) NOT NULL DEFAULT '',
          `viewdate` datetime DEFAULT NULL,
          `projectid` int(11) NOT NULL DEFAULT '0',
          `subproject` int(11) NOT NULL DEFAULT '0',
          `deptid` int(10) NOT NULL DEFAULT '0',
          `tax` int(11) NOT NULL DEFAULT '0',
          `shipcontactid` int(11) NOT NULL DEFAULT '0',
          `billcontactid` int(11) NOT NULL DEFAULT '0',
          `empid` int(11) NOT NULL DEFAULT '0',
          `sotrno` int(11) NOT NULL DEFAULT '0',
          `shipid` int(11) NOT NULL DEFAULT '0',
          `billid` int(11) NOT NULL DEFAULT '0',
          `revision` varchar(100) NOT NULL DEFAULT '',
          `deldate` datetime DEFAULT NULL,
          `deladdress` varchar(200) NOT NULL DEFAULT '',
          `rqtrno` int(11) NOT NULL DEFAULT '0',
          PRIMARY KEY (`trno`),
          KEY `Index_2head` (`docno`,`client`,`dateid`,`due`)
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("hpfhead", $qry);

    $qry = "CREATE TABLE `pfstock` (
          `trno` bigint(20) NOT NULL DEFAULT '0',
          `line` int(11) NOT NULL DEFAULT '0',
          `uom` varchar(15) NOT NULL DEFAULT '',
          `disc` varchar(40) NOT NULL DEFAULT '',
          `rem` varchar(40) NOT NULL DEFAULT '',
          `cost` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `rrqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `rrcost` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `qty` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `ext` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `qa` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `void` tinyint(1) NOT NULL DEFAULT '0',
          `refx` bigint(20) NOT NULL DEFAULT '0',
          `linex` int(11) NOT NULL DEFAULT '0',
          `ref` varchar(50) NOT NULL DEFAULT '',
          `encodeddate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          `encodedby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `editby` varchar(100) NOT NULL DEFAULT '',
          `sku` varchar(45) DEFAULT NULL,
          `loc` varchar(20) NOT NULL DEFAULT '',
          `kgs` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `cdrefx` bigint(20) NOT NULL DEFAULT '0',
          `cdlinex` int(11) NOT NULL DEFAULT '0',
          `itemid` int(11) NOT NULL DEFAULT '0',
          `whid` int(11) NOT NULL DEFAULT '0',
          `stageid` int(11) NOT NULL DEFAULT '0',
          `sorefx` int(11) NOT NULL DEFAULT '0',
          `solinex` int(11) NOT NULL DEFAULT '0',
          `projectid` int(3) NOT NULL DEFAULT '0',
          `osrefx` int(11) NOT NULL DEFAULT '0',
          `oslinex` int(11) NOT NULL DEFAULT '0',
          `sgdrate` decimal(18,6) NOT NULL DEFAULT '0.000000',
          `poref` varchar(30) NOT NULL DEFAULT '',
          PRIMARY KEY (`trno`,`line`),
          KEY `Index_2barcode` (`uom`)
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("pfstock", $qry);

    $qry = "CREATE TABLE `hpfstock` (
          `trno` bigint(20) NOT NULL DEFAULT '0',
          `line` int(11) NOT NULL DEFAULT '0',
          `uom` varchar(15) NOT NULL DEFAULT '',
          `disc` varchar(40) NOT NULL DEFAULT '',
          `rem` varchar(40) NOT NULL DEFAULT '',
          `cost` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `rrqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `rrcost` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `qty` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `ext` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `qa` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `void` tinyint(1) NOT NULL DEFAULT '0',
          `refx` bigint(20) NOT NULL DEFAULT '0',
          `linex` int(11) NOT NULL DEFAULT '0',
          `ref` varchar(50) NOT NULL DEFAULT '',
          `length` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `width` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `wt` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `iqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `encodeddate` datetime DEFAULT NULL,
          `encodedby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `editby` varchar(100) NOT NULL DEFAULT '',
          `sku` varchar(45) DEFAULT NULL,
          `loc` varchar(20) NOT NULL DEFAULT '',
          `kgs` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `cdrefx` bigint(20) NOT NULL DEFAULT '0',
          `cdlinex` int(11) NOT NULL DEFAULT '0',
          `itemid` int(11) NOT NULL DEFAULT '0',
          `whid` int(11) NOT NULL DEFAULT '0',
          `stageid` int(11) NOT NULL DEFAULT '0',
          `sorefx` int(11) NOT NULL DEFAULT '0',
          `solinex` int(11) NOT NULL DEFAULT '0',
          `projectid` int(3) NOT NULL DEFAULT '0',
          `osrefx` int(11) NOT NULL DEFAULT '0',
          `oslinex` int(11) NOT NULL DEFAULT '0',
          `sgdrate` decimal(18,6) NOT NULL DEFAULT '0.000000',
          `poref` varchar(30) NOT NULL DEFAULT '',
          PRIMARY KEY (`trno`,`line`),
          KEY `Index_2barcode` (`uom`)
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("hpfstock", $qry);

    $qry = "CREATE TABLE `rahead` (
          `trno` bigint(20) unsigned NOT NULL DEFAULT '0',
          `doc` char(2) NOT NULL DEFAULT '',
          `docno` char(20) NOT NULL DEFAULT '',
          `client` varchar(20) NOT NULL DEFAULT '',
          `clientname` varchar(150) NOT NULL DEFAULT '',
          `address` varchar(150) NOT NULL DEFAULT '',
          `shipto` varchar(150) NOT NULL DEFAULT '',
          `dateid` datetime DEFAULT NULL,
          `due` date DEFAULT NULL,
          `terms` varchar(30) NOT NULL DEFAULT '',
          `wh` varchar(20) NOT NULL DEFAULT '',
          `rem` varchar(500) NOT NULL DEFAULT '',
          `cur` varchar(3) NOT NULL DEFAULT '',
          `forex` decimal(18,4) NOT NULL DEFAULT '0.0000',
          `voiddate` datetime DEFAULT NULL,
          `branch` int(10) NOT NULL DEFAULT '0',
          `contra` varchar(100) NOT NULL DEFAULT '',
          `ourref` varchar(50) NOT NULL DEFAULT '',
          `agent` varchar(20) NOT NULL DEFAULT '',
          `yourref` varchar(50) NOT NULL DEFAULT '',
          `waybill` varchar(50) NOT NULL DEFAULT '',
          `deldate` datetime DEFAULT NULL,
          `delby` varchar(150) NOT NULL DEFAULT '',
          `tax` decimal(18,0) NOT NULL DEFAULT '0',
          `isimport` tinyint(4) NOT NULL DEFAULT '0',
          `charges` decimal(18,2) NOT NULL DEFAULT '0.00',
          `prepared` varchar(50) NOT NULL DEFAULT '',
          `approved` varchar(45) NOT NULL DEFAULT '',
          `checked` varchar(45) NOT NULL DEFAULT '',
          `comm` varchar(10) NOT NULL DEFAULT '',
          `factor` decimal(18,2) NOT NULL DEFAULT '0.00',
          `project` varchar(50) NOT NULL DEFAULT '',
          `vattype` varchar(45) NOT NULL DEFAULT '',
          `lockuser` varchar(100) NOT NULL DEFAULT '',
          `lockdate` datetime DEFAULT NULL,
          `openby` varchar(100) NOT NULL DEFAULT '',
          `users` varchar(100) NOT NULL DEFAULT '',
          `createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          `createby` varchar(100) NOT NULL DEFAULT '',
          `editby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `viewby` varchar(100) NOT NULL DEFAULT '',
          `viewdate` datetime DEFAULT NULL,
          `modeofpayment` varchar(40) DEFAULT '',
          `acctname` varchar(80) DEFAULT '',
          `acctno` varchar(40) DEFAULT '',
          `cardtype` varchar(40) DEFAULT '',
          `waybilldate` date DEFAULT NULL,
          `billlading` varchar(50) NOT NULL DEFAULT '',
          `voyage` varchar(50) NOT NULL DEFAULT '',
          `salestype` varchar(25) NOT NULL DEFAULT '',
          `trpricegrp` varchar(45) NOT NULL DEFAULT '',
          `trroute` int(10) unsigned NOT NULL DEFAULT '0',
          `invoiceno` varchar(25) NOT NULL DEFAULT '',
          `invoicedate` varchar(45) NOT NULL DEFAULT '',
          `trnxtype` varchar(45) NOT NULL DEFAULT '',
          `projectid` int(10) DEFAULT '0',
          `sjtag` int(10) unsigned NOT NULL DEFAULT '0',
          `cmtrans` int(10) NOT NULL DEFAULT '0',
          `pickby` varchar(45) NOT NULL DEFAULT '',
          `checkby` varchar(45) NOT NULL DEFAULT '',
          `gm_purchasetype` varchar(45) NOT NULL DEFAULT '',
          `ms_arastre` decimal(19,2) NOT NULL DEFAULT '0.00',
          `ms_freight` decimal(19,2) NOT NULL DEFAULT '0.00',
          `ms_wharffage` decimal(19,2) NOT NULL DEFAULT '0.00',
          `picker` varchar(45) NOT NULL DEFAULT '',
          `checker` varchar(45) NOT NULL DEFAULT '',
          `ewt` varchar(45) NOT NULL DEFAULT '',
          `ewtrate` int(10) NOT NULL DEFAULT '0',
          `uv_transtype` varchar(25) NOT NULL DEFAULT '',
          `mlcp_jonum` varchar(45) NOT NULL DEFAULT '',
          `mlcp_freight` varchar(45) NOT NULL DEFAULT '',
          `truck` varchar(50) NOT NULL DEFAULT '',
          `pctrno` int(10) unsigned NOT NULL DEFAULT '0',
          `creditinfo` varchar(1000) NOT NULL DEFAULT '',
          `crline` decimal(18,2) NOT NULL DEFAULT '0.00',
          `overdue` decimal(18,2) NOT NULL DEFAULT '0.00',
          `subproject` int(11) NOT NULL DEFAULT '0',
          `pltrno` int(11) NOT NULL DEFAULT '0',
          `customername` varchar(150) NOT NULL DEFAULT '',
          `deliverytype` int(11) NOT NULL DEFAULT '0',
          `projectto` int(11) NOT NULL DEFAULT '0',
          `subprojectto` int(11) NOT NULL DEFAULT '0',
          `partreqtypeid` int(11) NOT NULL DEFAULT '0',
          `brtrno` int(11) DEFAULT '0',
          `shipid` int(11) NOT NULL DEFAULT '0',
          `billid` int(11) NOT NULL DEFAULT '0',
          `tel` varchar(50) NOT NULL DEFAULT '',
          `deptid` int(10) NOT NULL DEFAULT '0',
          `statid` int(3) NOT NULL DEFAULT '0',
          `taxdef` decimal(18,6) NOT NULL DEFAULT '0.000000',
          `shipcontactid` int(11) NOT NULL DEFAULT '0',
          `billcontactid` int(11) NOT NULL DEFAULT '0',
          `qttrno` int(11) NOT NULL DEFAULT '0',
          `whref` varchar(20) NOT NULL DEFAULT '',
          PRIMARY KEY (`trno`),
          KEY `Index_4` (`client`),
          KEY `Index_6` (`doc`),
          KEY `Index_dateid` (`dateid`) USING BTREE,
          KEY `Index_doc` (`doc`) USING BTREE,
          KEY `Index_agent` (`agent`) USING BTREE,
          KEY `Index_5` (`docno`)
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("rahead", $qry);

    $qry = "CREATE TABLE `hrahead` (
          `trno` bigint(20) unsigned NOT NULL DEFAULT '0',
          `doc` char(2) NOT NULL DEFAULT '',
          `docno` char(20) NOT NULL,
          `clientid` int(11) NOT NULL DEFAULT '0',
          `clientname` varchar(150) NOT NULL DEFAULT '',
          `address` varchar(150) NOT NULL DEFAULT '',
          `shipto` varchar(150) NOT NULL DEFAULT '',
          `dateid` datetime DEFAULT NULL,
          `due` date DEFAULT NULL,
          `terms` varchar(30) NOT NULL DEFAULT '',
          `whid` int(11) NOT NULL DEFAULT '0',
          `rem` varchar(1000) NOT NULL,
          `cur` varchar(3) NOT NULL DEFAULT '',
          `forex` decimal(18,4) NOT NULL DEFAULT '0.0000',
          `voiddate` datetime DEFAULT NULL,
          `branch` int(10) NOT NULL DEFAULT '0',
          `contra` varchar(30) NOT NULL DEFAULT '',
          `ourref` varchar(50) NOT NULL DEFAULT '',
          `agentid` int(11) NOT NULL DEFAULT '0',
          `yourref` varchar(50) NOT NULL DEFAULT '',
          `waybill` varchar(50) NOT NULL DEFAULT '',
          `deldate` datetime DEFAULT NULL,
          `delby` varchar(150) NOT NULL DEFAULT '',
          `tax` decimal(18,0) NOT NULL DEFAULT '0',
          `isimport` tinyint(4) NOT NULL DEFAULT '0',
          `charges` decimal(18,2) NOT NULL DEFAULT '0.00',
          `prepared` varchar(50) NOT NULL DEFAULT '',
          `approved` varchar(45) NOT NULL DEFAULT '',
          `Checked` varchar(45) NOT NULL DEFAULT '',
          `comm` varchar(10) NOT NULL DEFAULT '',
          `factor` decimal(18,2) NOT NULL DEFAULT '0.00',
          `project` varchar(50) NOT NULL DEFAULT '',
          `VatType` varchar(45) NOT NULL DEFAULT '',
          `lockuser` varchar(100) NOT NULL DEFAULT '',
          `lockdate` datetime DEFAULT NULL,
          `openby` varchar(100) NOT NULL DEFAULT '',
          `users` varchar(100) NOT NULL DEFAULT '',
          `createdate` datetime DEFAULT NULL,
          `createby` varchar(100) NOT NULL DEFAULT '',
          `editby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `viewby` varchar(100) NOT NULL DEFAULT '',
          `viewdate` datetime DEFAULT NULL,
          `modeofpayment` varchar(40) DEFAULT '',
          `acctname` varchar(80) DEFAULT '',
          `acctno` varchar(40) DEFAULT '',
          `cardtype` varchar(40) DEFAULT '',
          `waybilldate` date DEFAULT NULL,
          `billlading` varchar(50) NOT NULL DEFAULT '',
          `voyage` varchar(50) NOT NULL DEFAULT '',
          `salestype` varchar(25) NOT NULL DEFAULT '',
          `trpricegrp` varchar(45) NOT NULL DEFAULT '',
          `trroute` int(10) unsigned NOT NULL DEFAULT '0',
          `invoiceno` varchar(25) NOT NULL DEFAULT '',
          `invoicedate` varchar(45) NOT NULL DEFAULT '',
          `trnxtype` varchar(45) NOT NULL DEFAULT '',
          `projectid` int(10) unsigned NOT NULL DEFAULT '0',
          `invtagging` int(10) DEFAULT '0',
          `cmtrans` int(10) NOT NULL DEFAULT '0',
          `pickby` varchar(45) NOT NULL DEFAULT '',
          `checkby` varchar(45) NOT NULL DEFAULT '',
          `gm_purchasetype` varchar(45) NOT NULL DEFAULT '',
          `ms_arastre` decimal(19,2) NOT NULL DEFAULT '0.00',
          `ms_freight` decimal(19,2) NOT NULL DEFAULT '0.00',
          `ms_wharffage` decimal(19,2) NOT NULL DEFAULT '0.00',
          `picker` varchar(45) NOT NULL DEFAULT '',
          `checker` varchar(45) NOT NULL DEFAULT '',
          `pickerid` varchar(45) NOT NULL DEFAULT '',
          `checkerid` varchar(45) NOT NULL DEFAULT '',
          `ewt` varchar(45) NOT NULL DEFAULT '',
          `ewtrate` int(10) NOT NULL DEFAULT '0',
          `uv_transtype` varchar(25) NOT NULL DEFAULT '',
          `mlcp_jonum` varchar(45) NOT NULL DEFAULT '',
          `mlcp_freight` varchar(45) NOT NULL DEFAULT '',
          `truck` varchar(50) NOT NULL DEFAULT '',
          `pctrno` int(10) unsigned NOT NULL DEFAULT '0',
          `creditinfo` varchar(1000) NOT NULL DEFAULT '',
          `crline` decimal(18,2) NOT NULL DEFAULT '0.00',
          `overdue` decimal(18,2) NOT NULL DEFAULT '0.00',
          `syid` int(11) NOT NULL DEFAULT '0',
          `periodid` int(11) NOT NULL DEFAULT '0',
          `courseid` int(11) NOT NULL DEFAULT '0',
          `semid` int(11) NOT NULL DEFAULT '0',
          `sectionid` int(11) NOT NULL DEFAULT '0',
          `yr` varchar(45) NOT NULL DEFAULT '',
          `levelid` int(11) NOT NULL DEFAULT '0',
          `deptid` int(11) NOT NULL DEFAULT '0',
          `sotrno` int(11) NOT NULL DEFAULT '0',
          `assessref` varchar(45) NOT NULL DEFAULT '',
          `encodeddate` datetime DEFAULT NULL,
          `encodedby` varchar(100) NOT NULL DEFAULT '',
          `subproject` int(11) NOT NULL DEFAULT '0',
          `pltrno` int(11) NOT NULL DEFAULT '0',
          `customername` varchar(150) NOT NULL DEFAULT '',
          `deliverytype` int(11) NOT NULL DEFAULT '0',
          `disc` decimal(18,2) NOT NULL DEFAULT '0.00',
          `projectto` int(11) NOT NULL DEFAULT '0',
          `subprojectto` int(11) NOT NULL DEFAULT '0',
          `partreqtypeid` int(11) NOT NULL DEFAULT '0',
          `brtrno` int(11) DEFAULT '0',
          `shipid` int(11) NOT NULL DEFAULT '0',
          `billid` int(11) NOT NULL DEFAULT '0',
          `tel` varchar(50) NOT NULL DEFAULT '',
          `isdropped` tinyint(4) unsigned NOT NULL DEFAULT '0',
          `statid` int(3) NOT NULL DEFAULT '0',
          `taxdef` decimal(18,6) NOT NULL DEFAULT '0.000000',
          `shipcontactid` int(11) NOT NULL DEFAULT '0',
          `billcontactid` int(11) NOT NULL DEFAULT '0',
          `ischinese` tinyint(4) unsigned NOT NULL DEFAULT '0',
          `qttrno` int(11) NOT NULL DEFAULT '0',
          `whref` varchar(20) NOT NULL DEFAULT '',
          PRIMARY KEY (`trno`),
          KEY `Index_4` (`clientid`),
          KEY `Index_6` (`doc`),
          KEY `Index_dateid` (`dateid`) USING BTREE,
          KEY `Index_doc` (`doc`) USING BTREE,
          KEY `Index_agent` (`agentid`) USING BTREE,
          KEY `Index_5` (`docno`)
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("hrahead", $qry);

    $qry = "CREATE TABLE `rastock` (
          `trno` bigint(20) unsigned NOT NULL DEFAULT '0',
          `line` int(11) NOT NULL,
          `refx` bigint(20) unsigned NOT NULL DEFAULT '0',
          `linex` int(11) NOT NULL DEFAULT '0',
          `uom` varchar(15) NOT NULL DEFAULT '',
          `disc` varchar(40) NOT NULL DEFAULT '',
          `rem` varchar(500) NOT NULL DEFAULT '',
          `rrcost` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `cost` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `rrqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `qty` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `isamt` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `amt` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `isqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `iss` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `ext` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `qa` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `ref` char(50) NOT NULL DEFAULT '',
          `void` tinyint(4) NOT NULL DEFAULT '0',
          `encodeddate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
          `encodedby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `editby` varchar(100) NOT NULL DEFAULT '',
          `loc` varchar(45) NOT NULL DEFAULT '',
          `loc2` varchar(45) NOT NULL DEFAULT '',
          `sku` varchar(45) DEFAULT NULL,
          `tstrno` int(10) unsigned NOT NULL DEFAULT '0',
          `tsline` int(10) unsigned NOT NULL DEFAULT '0',
          `comm` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `icomm` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `expiry` varchar(45) DEFAULT NULL,
          `isqty2` decimal(19,6) DEFAULT '0.000000',
          `iscomponent` int(1) unsigned NOT NULL DEFAULT '0',
          `outputid` int(10) unsigned NOT NULL DEFAULT '0',
          `iss2` decimal(19,6) DEFAULT '0.000000',
          `agent` varchar(45) NOT NULL DEFAULT '',
          `agent2` varchar(45) NOT NULL DEFAULT '',
          `isextract` int(1) unsigned NOT NULL DEFAULT '0',
          `outputline` int(11) unsigned NOT NULL DEFAULT '0',
          `tsako` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `msako` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `itemcomm` varchar(45) NOT NULL DEFAULT '',
          `itemhandling` varchar(45) NOT NULL DEFAULT '',
          `kgs` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `isfromjo` int(1) NOT NULL DEFAULT '0',
          `original_qty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `jotrno` int(11) NOT NULL DEFAULT '0',
          `joline` int(11) NOT NULL DEFAULT '0',
          `fcost` decimal(18,6) NOT NULL DEFAULT '0.000000',
          `itemid` int(11) NOT NULL DEFAULT '0',
          `whid` int(11) NOT NULL DEFAULT '0',
          `rebate` decimal(18,2) NOT NULL DEFAULT '0.00',
          `stageid` int(11) NOT NULL DEFAULT '0',
          `palletid` int(11) NOT NULL DEFAULT '0',
          `locid` int(11) NOT NULL DEFAULT '0',
          `palletid2` int(11) NOT NULL DEFAULT '0',
          `locid2` int(11) NOT NULL DEFAULT '0',
          `pickerid` int(11) NOT NULL DEFAULT '0',
          `pickerstart` datetime DEFAULT NULL,
          `pickerend` datetime DEFAULT NULL,
          `forkliftid` int(11) NOT NULL DEFAULT '0',
          `isforklift` tinyint(2) NOT NULL DEFAULT '0',
          `whmanid` int(11) NOT NULL DEFAULT '0',
          `whmandate` datetime DEFAULT NULL,
          `suppid` int(11) NOT NULL DEFAULT '0',
          `itemstatus` varchar(20) NOT NULL DEFAULT '',
          `projectid` int(3) NOT NULL DEFAULT '0',
          `sorefx` int(11) NOT NULL DEFAULT '0',
          `solinex` int(11) NOT NULL DEFAULT '0',
          `isapprove` tinyint(2) NOT NULL DEFAULT '0',
          `sgdrate` decimal(18,6) NOT NULL DEFAULT '0.000000',
          `poref` varchar(30) NOT NULL DEFAULT '',
          `noprint` tinyint(2) unsigned NOT NULL DEFAULT '0',
          `podate` datetime DEFAULT NULL,
          `agentid` int(11) NOT NULL DEFAULT '0',
          PRIMARY KEY (`trno`,`line`),
          KEY `Index_2stock` (`uom`,`loc`,`loc2`),
          KEY `Index_refx` (`refx`,`linex`),
          KEY `Index_loc` (`loc`),
          KEY `Index_trno` (`trno`,`void`,`loc`,`qty`,`iss`) USING BTREE
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("rastock", $qry);

    $qry = "CREATE TABLE `hrastock` (
          `trno` bigint(20) unsigned NOT NULL DEFAULT '0',
          `line` int(11) NOT NULL DEFAULT '0',
          `refx` bigint(20) unsigned NOT NULL DEFAULT '0',
          `linex` int(11) NOT NULL DEFAULT '0',
          `itemid` int(11) NOT NULL DEFAULT '0',
          `uom` varchar(15) NOT NULL DEFAULT '',
          `whid` int(11) NOT NULL DEFAULT '0',
          `disc` varchar(40) NOT NULL DEFAULT '',
          `rem` varchar(500) NOT NULL DEFAULT '',
          `rrcost` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `cost` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `rrqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `qty` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `isamt` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `amt` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `isqty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `iss` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `ext` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `qa` decimal(19,10) NOT NULL DEFAULT '0.0000000000',
          `ref` char(50) NOT NULL DEFAULT '',
          `void` tinyint(4) NOT NULL DEFAULT '0',
          `encodeddate` datetime DEFAULT NULL,
          `encodedby` varchar(100) NOT NULL DEFAULT '',
          `editdate` datetime DEFAULT NULL,
          `editby` varchar(100) NOT NULL DEFAULT '',
          `loc` varchar(45) NOT NULL DEFAULT '',
          `loc2` varchar(45) NOT NULL DEFAULT '',
          `sku` varchar(45) DEFAULT NULL,
          `tstrno` int(10) unsigned NOT NULL DEFAULT '0',
          `tsline` int(10) unsigned NOT NULL DEFAULT '0',
          `comm` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `icomm` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `expiry` varchar(45) DEFAULT NULL,
          `iss2` decimal(19,6) DEFAULT '0.000000',
          `agentid` int(10) unsigned NOT NULL DEFAULT '0',
          `agentid2` int(10) unsigned NOT NULL DEFAULT '0',
          `isqty2` decimal(19,6) DEFAULT '0.000000',
          `iscomponent` int(1) unsigned NOT NULL DEFAULT '0',
          `outputid` int(10) unsigned NOT NULL DEFAULT '0',
          `isextract` int(1) unsigned NOT NULL DEFAULT '0',
          `outputline` int(11) unsigned NOT NULL DEFAULT '0',
          `tsako` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `msako` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `itemcomm` varchar(45) NOT NULL DEFAULT '',
          `itemhandling` varchar(45) NOT NULL DEFAULT '',
          `kgs` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `isfromjo` int(1) NOT NULL DEFAULT '0',
          `original_qty` decimal(19,6) NOT NULL DEFAULT '0.000000',
          `jotrno` int(11) NOT NULL DEFAULT '0',
          `joline` int(11) NOT NULL DEFAULT '0',
          `fcost` decimal(18,6) NOT NULL DEFAULT '0.000000',
          `rebate` decimal(18,2) NOT NULL DEFAULT '0.00',
          `stageid` int(11) NOT NULL DEFAULT '0',
          `palletid` int(11) NOT NULL DEFAULT '0',
          `locid` int(11) NOT NULL DEFAULT '0',
          `palletid2` int(11) NOT NULL DEFAULT '0',
          `locid2` int(11) NOT NULL DEFAULT '0',
          `pickerid` int(11) NOT NULL DEFAULT '0',
          `pickerstart` datetime DEFAULT NULL,
          `pickerend` datetime DEFAULT NULL,
          `whmanid` int(11) NOT NULL DEFAULT '0',
          `whmandate` datetime DEFAULT NULL,
          `forkliftid` int(11) NOT NULL DEFAULT '0',
          `suppid` int(11) NOT NULL DEFAULT '0',
          `itemstatus` varchar(20) NOT NULL DEFAULT '',
          `projectid` int(3) NOT NULL DEFAULT '0',
          `sorefx` int(11) NOT NULL DEFAULT '0',
          `solinex` int(11) NOT NULL DEFAULT '0',
          `isapprove` tinyint(2) NOT NULL DEFAULT '0',
          `sgdrate` decimal(18,6) NOT NULL DEFAULT '0.000000',
          `poref` varchar(30) NOT NULL DEFAULT '',
          `noprint` tinyint(2) unsigned NOT NULL DEFAULT '0',
          `podate` datetime DEFAULT NULL,
          PRIMARY KEY (`trno`,`line`),
          KEY `Index_2stock` (`itemid`,`whid`,`uom`,`loc`),
          KEY `Index_refx` (`refx`,`linex`),
          KEY `Index_loc` (`whid`,`loc`),
          KEY `Index_trno` (`trno`,`itemid`,`whid`) USING BTREE
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
    $this->coreFunctions->sbccreatetable("hrastock", $qry);

    $qry = "CREATE TABLE `rrfams` (
          `trno` int(11) unsigned NOT NULL DEFAULT '0',
          `line` int(11) unsigned NOT NULL DEFAULT '0',
          `itemid` int(11) unsigned NOT NULL DEFAULT '0',
          `ajtrno` int(11) unsigned NOT NULL DEFAULT '0',
          `ajline` int(11) unsigned NOT NULL DEFAULT '0',
          `qty` decimal(18,6) unsigned NOT NULL DEFAULT '0.000000',
          `serialno` varchar(50) NOT NULL DEFAULT '',
          PRIMARY KEY (`trno`, `line`, `itemid`),
          KEY `Index_Trno` (`trno`),
          KEY `Index_Line` (`line`),
          KEY `Index_ItemID` (`itemid`),
          KEY `Index_AJRef` (`ajtrno`, `ajline`)
          ) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
    $this->coreFunctions->sbccreatetable("rrfams", $qry);

    $qry = "CREATE TABLE `hrrfams` (
          `trno` int(11) unsigned NOT NULL DEFAULT '0',
          `line` int(11) unsigned NOT NULL DEFAULT '0',
          `itemid` int(11) unsigned NOT NULL DEFAULT '0',
          `ajtrno` int(11) unsigned NOT NULL DEFAULT '0',
          `ajline` int(11) unsigned NOT NULL DEFAULT '0',
          `qty` decimal(18,6) unsigned NOT NULL DEFAULT '0.000000',
          `serialno` varchar(50) NOT NULL DEFAULT '',
          PRIMARY KEY (`trno`, `line`, `itemid`),
          KEY `Index_Trno` (`trno`),
          KEY `Index_Line` (`line`),
          KEY `Index_ItemID` (`itemid`),
          KEY `Index_AJRef` (`ajtrno`, `ajline`)
          ) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
    $this->coreFunctions->sbccreatetable("hrrfams", $qry);


    $this->coreFunctions->sbcaddcolumn("rrfams", "isnsi", "tinyint(1) NOT NULL DEFAULT '0'");
    $this->coreFunctions->sbcaddcolumn("hrrfams", "isnsi", "tinyint(1) NOT NULL DEFAULT '0'");
    $this->coreFunctions->sbcaddcolumn("reqcategory", "isnsi", "tinyint(1) NOT NULL DEFAULT '0'");
    $this->coreFunctions->sbcaddcolumn("reqcategory", "ists", "tinyint(2) NOT NULL DEFAULT '0'");
    $this->coreFunctions->sbcaddcolumn("reqcategory", "isgeneratefa", "tinyint(2) NOT NULL DEFAULT '0'");

    $this->coreFunctions->sbcaddcolumn("issueitem", "trno", "int NOT NULL DEFAULT '0'", 0);
    $this->coreFunctions->sbcaddcolumn("issueitem", "docno", "varchar(20) NOT NULL DEFAULT ''", 0);
    $this->coreFunctions->sbcaddcolumn("issueitem", "doc", "char(2) NOT NULL DEFAULT ''", 0);
    $this->coreFunctions->sbcaddcolumn("issueitem", "editby", "varchar(100) NOT NULL DEFAULT ''", 0);
    $this->coreFunctions->sbcaddcolumn("issueitem", "editdate", "datetime DEFAULT NULL", 0);
    $this->coreFunctions->sbcaddcolumn("issueitem", "viewby", "varchar(100) NOT NULL DEFAULT ''", 0);
    $this->coreFunctions->sbcaddcolumn("issueitem", "viewdate", "datetime DEFAULT NULL", 0);
    $this->coreFunctions->sbcaddcolumn("issueitem", "lockuser", "varchar(100) NOT NULL DEFAULT ''", 0);
    $this->coreFunctions->sbcaddcolumn("issueitem", "lockdate", "datetime DEFAULT NULL", 0);

    $this->coreFunctions->sbcaddcolumn("iteminfo", "isuploaded", "tinyint(2) NOT NULL DEFAULT '0'");
    $this->coreFunctions->sbcaddcolumn("iteminfo", "isstrno", "int(11) NOT NULL DEFAULT '0'");

    $this->coreFunctions->sbcaddcolumn("issueitem", "isauto", "int(11) NOT NULL DEFAULT '0'");

    $this->coreFunctions->sbcaddcolumngrp(["rrfams", "hrrfams"], ['barcode', 'sku'], "varchar(50) NOT NULL DEFAULT ''", 0);

    // $this->coreFunctions->sbcaddcolumngrp(["rrfams", "hrrfams"], ["fline"], "int(11) AUTO_INCREMENT", 1);
  }
}
