<?php

namespace App\Http\Classes\builder;

use DB;
use Exception;
use Throwable;
use App\Http\Classes\othersClass;

class buttonClass
{
    protected $othersClass;

    public function __construct()
    {
        $this->othersClass = new othersClass;
    } //end fn

    private $buttons;

    public function buttonsArray()
    {
        $this->buttons = array(
            'load' => array(
                'type' => 'button',
                'name' => 'load',
                'icon' => 'save',
                'label' => 'load',
                'class' => 'btnhead',
                'tooltip' => '',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'save' => array(
                'type' => 'button',
                'name' => 'save',
                'icon' => 'save',
                'label' => 'Save',
                'class' => 'btnsave',
                'tooltip' => 'Save Changes',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'new' => array(
                'type' => 'button',
                'name' => 'new',
                'icon' => 'add_box',
                'label' => 'New',
                'class' => 'btnnew',
                'tooltip' => 'New Transaction',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => false,
                    'edit' => false,
                    'print' => false,
                    'save' => true,
                    'delete' => false,
                    'cancel' => true,
                    'logs' => false,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => false,
                    'toggledown' => false,
                    'backlisting' => false,
                    'help' => true,
                    'others' => true
                )
            ),
            'print' => array(
                'type' => 'button',
                'name' => 'print',
                'icon' => 'print',
                'label' => 'Print',
                'class' => 'btnprint',
                'tooltip' => 'Print Document',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'delete' => array(
                'type' => 'button',
                'name' => 'delete',
                'icon' => 'delete',
                'label' => 'Delete',
                'class' => 'btndelete',
                'tooltip' => 'Delete Document',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'post' => array(
                'type' => 'button',
                'name' => 'post',
                'icon' => 'check',
                'label' => 'Post',
                'class' => 'btnpost',
                'tooltip' => 'Post Document',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => false,
                    'print' => true,
                    'save' => false,
                    'delete' => false,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => true,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'unpost' => array(
                'type' => 'button',
                'name' => 'unpost',
                'icon' => 'settings_backup_restore',
                'label' => 'UnPost',
                'class' => 'btnpost',
                'tooltip' => 'Unpost Document',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => false,
                    'cancel' => false,
                    'logs' => true,
                    'post' => true,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'lock' => array(
                'type' => 'button',
                'name' => 'lock',
                'icon' => 'lock',
                'label' => 'Lock',
                'class' => 'btnlock',
                'tooltip' => 'Lock Document',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => false,
                    'print' => true,
                    'save' => false,
                    'delete' => false,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => true,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'unlock' => array(
                'type' => 'button',
                'name' => 'unlock',
                'icon' => 'lock_open',
                'label' => 'UnLock',
                'class' => 'btnlock',
                'tooltip' => 'Unlock Document',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => true,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'logs' => array(
                'type' => 'button',
                'name' => 'logs',
                'icon' => 'description',
                'label' => 'Logs',
                'class' => 'btnlogs',
                'tooltip' => 'View Logs',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'edit' => array(
                'type' => 'button',
                'name' => 'edit',
                'icon' => 'edit',
                'label' => 'Edit',
                'class' => 'btnedit',
                'tooltip' => 'Edit Document',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => false,
                    'edit' => false,
                    'print' => false,
                    'save' => true,
                    'delete' => false,
                    'cancel' => true,
                    'logs' => false,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => false,
                    'toggledown' => false,
                    'backlisting' => false,
                    'help' => true,
                    'others' => true
                )
            ),
            'cancel' => array(
                'type' => 'button',
                'name' => 'cancel',
                'icon' => 'cancel',
                'label' => 'Cancel',
                'class' => 'btncancel',
                'tooltip' => 'Cancel Changes',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'toggleup' => array(
                'type' => 'button',
                'name' => 'toggleup',
                'icon' => 'keyboard_arrow_up',
                'label' => '',
                'class' => 'btntoggle',
                'tooltip' => 'Hide Head',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => false,
                    'toggledown' => true,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'toggledown' => array(
                'type' => 'button',
                'name' => 'toggledown',
                'icon' => 'keyboard_arrow_down',
                'label' => '',
                'class' => 'btntoggle',
                'tooltip' => 'Show Head',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'backlisting' => array(
                'type' => 'button',
                'name' => 'backlisting',
                'icon' => 'exit_to_app',
                'label' => '',
                'class' => 'btnbacklisting',
                'tooltip' => 'Back To Listing',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'help' => array(
                'type' => 'dropdown',
                'name' => 'help',
                'icon' => 'exit_to_app',
                'label' => 'Help',
                'class' => 'btnhelp',
                'tooltip' => 'Help',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true
                )
            ),
            'others' => array(
                'type' => 'actionlist',
                'name' => 'others',
                'icon' => 'exit_to_app',
                'label' => 'Utilities',
                'class' => 'btnothers',
                'tooltip' => 'Others',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'actionload' => array(
                'type' => 'button',
                'name' => 'load',
                'icon' => 'save',
                'label' => 'load',
                'class' => 'btnhead',
                'tooltip' => '',
                'disable' => false,
                'visible' => true,
                'confirm' => true,
                'confirmlabel' => 'do you?',
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => true,
                    'print' => true,
                    'save' => false,
                    'delete' => true,
                    'cancel' => false,
                    'logs' => true,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => true,
                    'toggledown' => false,
                    'backlisting' => true,
                    'help' => true,
                    'others' => true
                )
            ),
            'posbtn' => array(
                'type' => 'button',
                'name' => 'posbtn',
                'icon' => '',
                'label' => '',
                'class' => '',
                'tooltip' => '',
                'disable' => false,
                'visible' => false,
                'vshow' => array(
                    'load' => false,
                    'new' => true,
                    'edit' => false,
                    'print' => false,
                    'save' => false,
                    'delete' => false,
                    'cancel' => false,
                    'logs' => false,
                    'post' => false,
                    'unpost' => false,
                    'lock' => false,
                    'unlock' => false,
                    'unpaid' => false,
                    'orders' => false,
                    'back' => false,
                    'toggleup' => false,
                    'toggledown' => false,
                    'backlisting' => false,
                    'help' => false,
                    'others' => false
                )
            )
        );
    }


    public function create($btns)
    {
        $this->buttonsArray();

        $btn = [];
        foreach ($btns as $key => $value) {
            $btn = $this->othersClass->array_add($btn, $value, $this->buttons[$value]);
        }
        return $btn;
    } // create
}
