<?php
namespace App\Http\Classes\builder;

use App\Http\Classes\othersClass;

class mobileButtonClass {

  private $othersClass;
  public function __construct() {
    $this->othersClass = new othersClass;
  }

  private $buttons = [
    'create'=>[
      'name'=>'create',
      'label'=>'New',
      'icon'=>'add',
      'func'=>'createDoc',
      'functype'=>'module'
    ],
    'save'=>[
      'name'=>'save',
      'label'=>'Save',
      'icon'=>'save',
      'func'=>'saveDoc',
      'functype'=>'module'
    ],
    'edit'=>[
      'name'=>'edit',
      'label'=>'Edit',
      'icon'=>'edit',
      'func'=>'editDoc',
      'functype'=>'module'
    ],
    'cancel'=>[
      'name'=>'cancel',
      'label'=>'Cancel',
      'icon'=>'cancel',
      'func'=>'cancelDoc',
      'functype'=>'module'
    ],
    'delete'=>[
      'name'=>'delete',
      'label'=>'Delete',
      'icon'=>'delete',
      'func'=>'deleteDoc',
      'functype'=>'module'
    ],
    'post'=>[
      'name'=>'post',
      'label'=>'Post',
      'icon'=>'check',
      'func'=>'postDoc',
      'functype'=>'module'
    ],
    'unpost'=>[
      'name'=>'unpost',
      'label'=>'UnPost',
      'icon'=>'settings_backup_restore',
      'func'=>'unPostDoc',
      'functype'=>'module'
    ],
    'back'=>[
      'name'=>'back',
      'label'=>'Back',
      'icon'=>'arrow_back',
      'func'=>'loadDocList',
      'functype'=>'module'
    ],
    'additem'=>[
      'name'=>'additem',
      'label'=>'Add Item',
      'icon'=>'add',
      'action'=>'lookup',
      'func'=>'itemlookup',
      'params'=>'[{ name: "type", value: "doc" }]',
      'functype'=>'module'
    ],
    'scan'=>[
      'name'=>'scan',
      'label'=>'Scan',
      'icon'=>'qr_code_scanner',
      'func'=>'scanItem',
      'functype'=>'module'
    ],
    'addqty'=>[
      'name'=>'addqty',
      'label'=>'',
      'color'=>'primary',
      'icon'=>'fa-solid fa-add',
      'func'=>'addSAPQty',
      'functype'=>'global',
      'class'=>'q-ml-sm',
      'style'=>'margin-left:10px;'
    ],
    'scanlist'=>[
      'name'=>'scanlist',
      'label'=>'Scan List',
      'icon'=>'document_scanner',
      'func'=>'scanSAPList',
      'functype'=>'global',
      'color'=>'primary'
    ],
    'viewscanlist'=>[
      'name'=>'viewscanlist',
      'label'=>'View Scan List',
      'icon'=>'fact_check',
      'func'=>'viewSAPScanList',
      'functype'=>'global',
      'color'=>'primary'
    ],
    'edititem'=>[
      'name'=>'edititem',
      'icon'=>'edit',
      'color'=>'primary',
      'func'=>'editStock',
      'functype'=>'module'
    ],
    'deleteitem'=>[
      'name'=>'deleteitem',
      'icon'=>'delete',
      'color'=>'negative',
      'func'=>'deleteStock',
      'functype'=>'module'
    ],
    'addrecord'=>[
      'name'=>'addrecord',
      'label'=>'Add Record',
      'icon'=>'add',
      'action'=>'func',
      'func'=>'addRecord',
      'functype'=>'module'
    ],
    'addrecord2'=>[
      'name'=>'addrecord2',
      'label'=>'Add Record2',
      'icon'=>'add',
      'action'=>'func',
      'func'=>'addRecord2',
      'functype'=>'module'
    ],
    'saverecord'=>[
      'name'=>'saverecord',
      'label'=>'Save',
      'color'=>'primary',
      'func'=>'saveRecord',
      'functype'=>'module'
    ],
    'cancelrecord'=>[
      'name'=>'cancelrecord',
      'label'=>'Cancel',
      'color'=>'negative',
      'func'=>'cancelRecord',
      'functype'=>'module'
    ],
    'editrecord'=>[
      'name'=>'editrecord',
      'icon'=>'edit',
      'color'=>'primary',
      'func'=>'editRecord',
      'functype'=>'module'
    ],
    'deleterecord'=>[
      'name'=>'deleterecord',
      'icon'=>'delete',
      'color'=>'negative',
      'func'=>'deleteRecord',
      'functype'=>'module'
    ],
    'addtocart'=>[
      'name'=>'addtocart',
      'icon'=>'shopping_cart',
      'label'=>'Add',
      'color'=>'primary',
      'func'=>'addToCart',
      'functype'=>'module'
    ],
    'ok'=>[
      'name'=>'ok',
      'label'=>'Ok',
      'color'=>'primary',
      'func'=>'addItemOk',
      'functype'=>'global'
    ],
    'close'=>[
      'name'=>'close',
      'label'=>'Close',
      'color'=>'negative',
      'func'=>'closeDialog',
      'functype'=>'module'
    ],
    'editcart'=>[
      'name'=>'editcart',
      'label'=>'',
      'color'=>'primary',
      'icon'=>'edit',
      'func'=>'editCart',
      'functype'=>'global'
    ],
    'deletecart'=>[
      'name'=>'deletecart',
      'label'=>'',
      'color'=>'negative',
      'icon'=>'delete',
      'func'=>'deleteCart',
      'functype'=>'global'
    ],
    'checkout'=>[
      'name'=>'checkout',
      'label'=>'Checkout',
      'color'=>'primary',
      'func'=>'checkout',
      'functype'=>'module'
    ],
    'editorder'=>[
      'name'=>'editorder',
      'icon'=>'edit',
      'color'=>'primary',
      'func'=>'editOrder',
      'functype'=>'module'
    ],
    'deleteorder'=>[
      'name'=>'deleteorder',
      'icon'=>'delete',
      'color'=>'negative',
      'func'=>'deleteOrder',
      'functype'=>'module'
    ],
    'vieworder'=>[
      'name'=>'vieworder',
      'icon'=>'visibility',
      'color'=>'primary',
      'func'=>'viewOrder',
      'functype'=>'module'
    ],
    'printorder'=>[
      'name'=>'printorder',
      'icon'=>'print',
      'color'=>'primary',
      'func'=>'printOrder',
      'functype'=>'module'
    ],
    'login'=>[
      'name'=>'login',
      'icon'=>'',
      'label'=>'Login',
      'color'=>'primary',
      'func'=>'login',
      'functype'=>'global'
    ],
    'download'=>[
      'name'=>'download',
      'icon'=>'download',
      'label'=>'Download',
      'color'=>'primary',
      'func'=>'downloadDoc',
      'functype'=>'global'
    ],
    'upload'=>[
      'name'=>'upload',
      'icon'=>'upload',
      'label'=>'',
      'color'=>'primary',
      'func'=>'uploadDocProd',
      'functype'=>'global'
    ],
    'viewdoc'=>[
      'name'=>'viewdoc',
      'icon'=>'visibility',
      'color'=>'primary',
      'func'=>'viewDoc',
      'functype'=>'global'
    ],
    'stockinfo'=>[
      'name'=>'stockinfo',
      'icon'=>'visibility',
      'color'=>'primary',
      'func'=>'clickStockProd',
      'functype'=>'global'
    ],
    'print'=>[
      'name'=>'print',
      'icon'=>'print',
      'label'=>'Print',
      'color'=>'primary',
      'func'=>'printSAPCode',
      'functype'=>'global'
    ],
    'generate'=>[
      'name'=>'generate',
      'icon'=>'app_registration',
      'label'=>'',
      'color'=>'white',
      'func'=>'generateInventory',
      'functype'=>'module'
    ],
    'senddoc'=>[
      'name'=>'senddoc',
      'icon'=>'attach_email',
      'label'=>'Send',
      'color'=>'primary',
      'func'=>'sendDocument',
      'functype'=>'module'
    ]
  ];

  public function create($btns) {
    $btn = [];
    foreach($btns as $key => $value) {
      $btn = $this->othersClass->array_add($btn, $value, $this->buttons[$value]);
    }
    return $btn;
  }

}
