#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
));

// use Symfony\Component\Console\Input\ArgvInput;

// define('LARAVEL_START', microtime(true));

// // Register the Composer autoloader...
// require __DIR__.'/vendor/autoload.php';

// // Bootstrap Laravel and handle the command...
// $status = (require_once __DIR__.'/bootstrap/app.php')
//     ->handleCommand(new ArgvInput);

// exit($status);
